# Generated by Django 4.2.2 on 2023-06-28 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data e krijimit')),
                ('date_last_updated', models.DateTimeField(auto_now=True, verbose_name='Data e modifikimit')),
                ('rating', models.PositiveIntegerField(verbose_name='Vlerësimi')),
            ],
            options={
                'verbose_name': 'Vlerësimi',
                'verbose_name_plural': 'Vlerësimet',
                'db_table': 'ra_feedback',
                'ordering': ['rating'],
            },
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data e krijimit')),
                ('date_last_updated', models.DateTimeField(auto_now=True, verbose_name='Data e modifikimit')),
                ('first_name', models.CharField(max_length=50, verbose_name='Emri')),
                ('last_name', models.CharField(max_length=50, verbose_name='Mbiemri')),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='model.feedback')),
            ],
            options={
                'verbose_name': 'Kamarieri',
                'verbose_name_plural': 'Kamarierët',
                'db_table': 'ra_waiter',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data e krijimit')),
                ('date_last_updated', models.DateTimeField(auto_now=True, verbose_name='Data e modifikimit')),
                ('name', models.CharField(max_length=150, verbose_name='Kategoria')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresa')),
                ('nipt', models.CharField(blank=True, max_length=25, null=True, verbose_name='NIPT')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='model.customuser')),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiters', to='model.waiter')),
            ],
            options={
                'verbose_name': 'Biznesi',
                'verbose_name_plural': 'Bizneset',
                'db_table': 'ra_business',
                'ordering': ['name'],
            },
        ),
    ]
