# Generated by Django 4.2.2 on 2023-06-28 10:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Emri i biznesit'),
        ),
        migrations.CreateModel(
            name='ACActionLogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Action time')),
                ('user_ip', models.CharField(blank=True, max_length=20, verbose_name='User IP')),
                ('object_id', models.TextField(blank=True, null=True, verbose_name='Object id')),
                ('object_repr', models.CharField(max_length=200, verbose_name='Object repr')),
                ('action_flag', models.PositiveSmallIntegerField(verbose_name='Action flag')),
                ('change_message', models.TextField(blank=True, verbose_name='Change message')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.customuser', verbose_name='CustomUser')),
            ],
            options={
                'verbose_name': 'Action Logger',
                'verbose_name_plural': 'Action Loggers',
                'db_table': 'action_logger',
            },
            managers=[
                ('objects', model.models.ACLogEntryManager()),
            ],
        ),
    ]
