# Generated by Django 4.2.2 on 2023-06-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_alter_business_name_acactionlogger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='business',
            name='waiter',
        ),
        migrations.AddField(
            model_name='customuser',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_admins', to='model.business'),
        ),
        migrations.AddField(
            model_name='waiter',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_waiters', to='model.business'),
        ),
    ]
