# Generated by Django 4.2.2 on 2023-06-28 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_remove_business_admin_remove_business_waiter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiter',
            name='feedback',
        ),
        migrations.AddField(
            model_name='feedback',
            name='waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='model.waiter'),
        ),
    ]
