# Generated by Django 4.2.2 on 2023-06-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_remove_waiter_feedback_feedback_waiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
