# Generated by Django 4.2.2 on 2023-07-06 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_waiter_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data e krijimit')),
                ('date_last_updated', models.DateTimeField(auto_now=True, verbose_name='Data e modifikimit')),
                ('rating', models.PositiveIntegerField(verbose_name='Vlerësimi')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_feedbacks', to='model.business')),
            ],
            options={
                'verbose_name': 'Vlerësimi për produktin',
                'verbose_name_plural': 'Vlerësimet për produktin',
                'db_table': 'ra_product_feedback',
                'ordering': ['rating'],
            },
        ),
        migrations.CreateModel(
            name='WaiterFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data e krijimit')),
                ('date_last_updated', models.DateTimeField(auto_now=True, verbose_name='Data e modifikimit')),
                ('rating', models.PositiveIntegerField(verbose_name='Vlerësimi')),
            ],
            options={
                'verbose_name': 'Vlerësimi për kamarierin',
                'verbose_name_plural': 'Vlerësimet për kamarierin',
                'db_table': 'ra_waiter_feedback',
                'ordering': ['rating'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='model.business'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiters', to='model.business'),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.AddField(
            model_name='waiterfeedback',
            name='waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiter_feedbacks', to='model.waiter'),
        ),
    ]
