# Generated by Django 4.2.2 on 2023-07-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_businessfeedback_remove_category_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='rating',
            field=models.ManyToManyField(blank=True, null=True, related_name='category_ratings', to='model.businessfeedback'),
        ),
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_ratings', to='model.businessfeedback'),
        ),
    ]
