# Generated by Django 4.2.2 on 2023-07-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_alter_category_rating_alter_products_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='products',
            name='rating',
        ),
        migrations.AddField(
            model_name='businessfeedback',
            name='category_rating',
            field=models.ManyToManyField(blank=True, null=True, related_name='category_ratings', to='model.category'),
        ),
        migrations.AddField(
            model_name='businessfeedback',
            name='product_rating',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_ratings', to='model.products'),
        ),
    ]
