# Generated by Django 4.2.2 on 2023-07-06 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_remove_category_rating_remove_products_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessfeedback',
            name='category_rating',
        ),
        migrations.RemoveField(
            model_name='businessfeedback',
            name='product_rating',
        ),
        migrations.AddField(
            model_name='businessfeedback',
            name='category_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_ratings', to='model.category'),
        ),
        migrations.AddField(
            model_name='businessfeedback',
            name='product_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='model.products'),
        ),
    ]
