# Generated by Django 4.2.2 on 2023-07-07 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0012_remove_businessfeedback_category_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data e krijimit')),
                ('date_last_updated', models.DateTimeField(auto_now=True, verbose_name='Data e modifikimit')),
                ('rating', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_ratings', to='model.category')),
            ],
            options={
                'verbose_name': 'Vlerësimi për kategorinë',
                'verbose_name_plural': 'Vlerësimet për kategorinë',
                'db_table': 'si_category_rating',
            },
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data e krijimit')),
                ('date_last_updated', models.DateTimeField(auto_now=True, verbose_name='Data e modifikimit')),
                ('rating', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Vlerësimi për produktin',
                'verbose_name_plural': 'Vlerësimet për produktin',
                'db_table': 'si_product_rating',
            },
        ),
        migrations.CreateModel(
            name='WaiterRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data e krijimit')),
                ('date_last_updated', models.DateTimeField(auto_now=True, verbose_name='Data e modifikimit')),
                ('rating', models.PositiveIntegerField(verbose_name='Vlerësimi')),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiter_ratings', to='model.waiter')),
            ],
            options={
                'verbose_name': 'Vlerësimi për kamarierin',
                'verbose_name_plural': 'Vlerësimet për kamarierin',
                'db_table': 'si_waiter_rating',
                'ordering': ['rating'],
            },
        ),
        migrations.RemoveField(
            model_name='waiterfeedback',
            name='waiter',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.DeleteModel(
            name='BusinessFeedback',
        ),
        migrations.DeleteModel(
            name='WaiterFeedback',
        ),
        migrations.AddField(
            model_name='productrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='model.product'),
        ),
    ]
