# Generated by Django 4.2.2 on 2023-07-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0013_categoryrating_productrating_waiterrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiterrating',
            name='client_device',
            field=models.CharField(default='none', max_length=10),
            preserve_default=False,
        ),
    ]
