# Generated by Django 4.2.2 on 2023-07-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0014_waiterrating_client_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiterrating',
            name='client_device',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
